### ISSUE TITLE
[Question] 最新的master启动不了

### ISSUE THREAD

**Issue by zhouliweb** [apache/incubator-hugegraph#1815]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: Hbase
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

```
2022-04-12 09:31:48 [main] [DEBUG] c.b.h.b.s.BackendStoreProvider - The 'hbase' StoreProvider load GraphStore 's'
Exception in thread "main" java.lang.NoClassDefFoundError: com/baidu/hugegraph/type/Namifiable
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.<init>(HugeGraphAuthProxy.java:1740)
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextThreadPoolExecutor.execute(HugeGraphAuthProxy.java:1765)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.eval(GremlinExecutor.java:307)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.lambda$new$4(ServerGremlinExecutor.java:141)
        at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:136)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:122)
        at com.baidu.hugegraph.auth.ContextGremlinServer.<init>(ContextGremlinServer.java:60)
        at com.baidu.hugegraph.dist.HugeGremlinServer.start(HugeGremlinServer.java:55)
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:59)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119)
NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80) [gremlin-server-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:122) [gremlin-server-3.4.3.jar:3.4.3]
        at com.baidu.hugegraph.auth.ContextGremlinServer.<init>(ContextGremlinServer.java:60) [hugegraph-api-0.12.0.jar:0.67.0.0]
        at com.baidu.hugegraph.dist.HugeGremlinServer.start(HugeGremlinServer.java:55) [hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:59) [hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119) [hugegraph-dist-0.12.0.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
        ... 15 more
Caused by: java.lang.AbstractMethodError: com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.newGraphStore(Lcom/baidu/hugegraph/config/HugeConfig;Ljava/lang/String;)Lcom/baidu/hugegraph/backend/store/BackendStore;
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.loadGraphStore(AbstractBackendStoreProvider.java:196) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.loadSystemStore(AbstractBackendStoreProvider.java:207) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.loadSystemStore(StandardHugeGraph.java:460) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.access$1300(StandardHugeGraph.java:112) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph$StandardHugeGraphParams.loadSystemStore(StandardHugeGraph.java:1178) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.ServerInfoManager.listenChanges(ServerInfoManager.java:109) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.ServerInfoManager.<init>(ServerInfoManager.java:85) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.StandardTaskScheduler.<init>(StandardTaskScheduler.java:106) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.addScheduler(TaskManager.java:92) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:217) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:87) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:68) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
        ... 15 more
2022-04-12 09:31:48 [main] [DEBUG] o.a.t.g.s.GremlinServer - GraphFactory exception
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:70) ~[gremlin-core-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:104) ~[gremlin-core-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671) [?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55) [gremlin-server-3.4.3.jar:3.4.3]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80) [gremlin-server-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:122) [gremlin-server-3.4.3.jar:3.4.3]
        at com.baidu.hugegraph.auth.ContextGremlinServer.<init>(ContextGremlinServer.java:60) [hugegraph-api-0.12.0.jar:0.67.0.0]
        at com.baidu.hugegraph.dist.HugeGremlinServer.start(HugeGremlinServer.java:55) [hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:59) [hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119) [hugegraph-dist-0.12.0.jar:?]
Caused by: java.lang.AbstractMethodError: com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.newGraphStore(Lcom/baidu/hugegraph/config/HugeConfig;Ljava/lang/String;)Lcom/baidu/hugegraph/backend/store/BackendStore;
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.loadGraphStore(AbstractBackendStoreProvider.java:196) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.loadSystemStore(AbstractBackendStoreProvider.java:207) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.loadSystemStore(StandardHugeGraph.java:460) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.access$1300(StandardHugeGraph.java:112) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph$StandardHugeGraphParams.loadSystemStore(StandardHugeGraph.java:1178) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.ServerInfoManager.listenChanges(ServerInfoManager.java:109) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.ServerInfoManager.<init>(ServerInfoManager.java:85) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.StandardTaskScheduler.<init>(StandardTaskScheduler.java:106) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.addScheduler(TaskManager.java:92) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:217) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:87) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:68) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        ... 20 more
2022-04-12 09:31:48 [main] [INFO] o.a.t.g.s.u.ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2022-04-12 09:31:49 [main] [INFO] o.a.t.g.s.u.ServerGremlinExecutor - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2022-04-12 09:31:49 [main] [DEBUG] o.a.t.g.g.e.GremlinExecutor - Preparing to evaluate script - 1+1 - in thread [main]
2022-04-12 09:31:50 [main] [ERROR] c.b.h.d.HugeGraphServer - HugeGremlinServer start error:
java.lang.NoClassDefFoundError: com/baidu/hugegraph/type/Namifiable
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.<init>(HugeGraphAuthProxy.java:1740) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextThreadPoolExecutor.execute(HugeGraphAuthProxy.java:1765) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.eval(GremlinExecutor.java:307) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.lambda$new$4(ServerGremlinExecutor.java:141) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559) ~[?:1.8.0_171]
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:136) ~[gremlin-server-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:122) ~[gremlin-server-3.4.3.jar:3.4.3]
        at com.baidu.hugegraph.auth.ContextGremlinServer.<init>(ContextGremlinServer.java:60) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
        at com.baidu.hugegraph.dist.HugeGremlinServer.start(HugeGremlinServer.java:55) ~[hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:59) ~[hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119) ~[hugegraph-dist-0.12.0.jar:?]
Caused by: java.lang.ClassNotFoundException: com.baidu.hugegraph.type.Namifiable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        ... 12 more
2022-04-12 09:31:50 [main] [DEBUG] c.b.h.e.EventHub - Destroy pool for EventHub
2022-04-12 09:31:50 [main] [INFO] c.b.h.HugeGraph - HugeFactory shutdown
2022-04-12 09:31:50 [hugegraph-shutdown] [INFO] c.b.h.HugeGraph - HugeGraph is shutting down
Exception in thread "gremlin-server-shutdown" java.lang.NullPointerException
        at com.baidu.hugegraph.auth.ContextGremlinServer.unlistenChanges(ContextGremlinServer.java:83)
        at com.baidu.hugegraph.auth.ContextGremlinServer.stop(ContextGremlinServer.java:92)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$new$0(GremlinServer.java:103)
        at java.lang.Thread.run(Thread.java:748)


### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

**Comment by imbajin** [comment]
`java.lang.NoClassDefFoundError: com/baidu/hugegraph/type/Namifiable` 

应该是包相关有啥异常把, 找一下这个类所在的包, 然后确认一下先. (或者对比一下 release 的包里这个 jar 有啥区别, 替换一下)
