### ISSUE TITLE
[Question] 调用K-Neighbor的api在需要执行较长时间时会报错

### ISSUE THREAD

**Issue by YT-FF** [apache/incubator-hugegraph#1817]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB, HDD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  Twitter-2010

### Your Question (问题描述)

执行3跳邻居报错，正确的返回结果应该有2kw+
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.AbstractRestClient.request(AbstractRestClient.java:199)
	at com.baidu.hugegraph.rest.AbstractRestClient.get(AbstractRestClient.java:296)
	at com.baidu.hugegraph.rest.AbstractRestClient.get(AbstractRestClient.java:275)
	at com.baidu.hugegraph.api.traverser.KneighborAPI.get(KneighborAPI.java:59)
	at com.baidu.hugegraph.driver.TraverserManager.kneighbor(TraverserManager.java:415)
	at com.cltech.performance.test.curd.test.main(test.java:22)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.rest.AbstractRestClient.lambda$get$3(AbstractRestClient.java:301)
	at com.baidu.hugegraph.rest.AbstractRestClient.request(AbstractRestClient.java:197)
	... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 17 more

**Comment by imbajin** [comment]
超时了吧, 调整一下 rest-api 超时时间, 或者异步执行, 详情参考历史 issue 有类似回复

**Comment by javeme** [comment]
超时配置修改可以参考：https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915
