### ISSUE TITLE
[Question]palo backend init error

### ISSUE THREAD

**Issue by mklzl** [apache/incubator-hugegraph#1873]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.13
- Backend: palo
- OS:  Centos 7.6

### Your Question (问题描述)

When I initialized the backend storage using Palo, I found that the configuration did not load correctly

 hugegraph.properties

```ini
    backend=palo
    serializer=palo
    store=hugegraph
    ...
    palo.host=192.168.1.xxx
    palo.http_port=xxxx
    palo.username=root
    palo.password=
    palo.poll_interval=10
    palo.temp_dir=./palo-data
    palo.file_limit_size=32
```

error info  :
  
```java
> Initializing HugeGraph Store...
2022-05-12 11:47:39 [main] [INFO] c.b.h.u.ConfigUtil - Scanning option 'graphs' directory './conf/graphs'
2022-05-12 11:47:39 [main] [INFO] c.b.h.c.InitStore - Init graph with config file: ./conf/graphs/hugegraph.properties
2022-05-12 11:47:39 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'users-hugegraph' with capacity 10240
2022-05-12 11:47:39 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'users_pwd-hugegraph' with capacity 10240
2022-05-12 11:47:39 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'token-hugegraph' with capacity 10240
2022-05-12 11:47:39 [main] [INFO] c.b.h.b.s.p.PaloStore - Open palo session pool for hugegraph/m
2022-05-12 11:47:40 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://127.0.0.1:3306/?socketTimeout=0&useSSL=false'
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to open schema transaction
        at com.baidu.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:417)
        at com.baidu.hugegraph.StandardHugeGraph.access$2600(StandardHugeGraph.java:112)
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.getOrNewTransaction(StandardHugeGraph.java:1388)
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.schemaTransaction(StandardHugeGraph.java:1364)
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.access$100(StandardHugeGraph.java:1234)
        at com.baidu.hugegraph.StandardHugeGraph.schemaTransaction(StandardHugeGraph.java:470)
        at com.baidu.hugegraph.StandardHugeGraph.backendStoreSystemInfo(StandardHugeGraph.java:249)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:94)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:79)
2022-05-12 11:47:40 [main] [ERROR] c.b.h.HugeGraph - Failed to open schema transaction
com.baidu.hugegraph.backend.BackendException: Failed to obtain database info
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:150) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlStore.open(MysqlStore.java:122) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:82) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:75) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:413) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.access$2600(StandardHugeGraph.java:112) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.getOrNewTransaction(StandardHugeGraph.java:1388) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.schemaTransaction(StandardHugeGraph.java:1364) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.access$100(StandardHugeGraph.java:1234) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.schemaTransaction(StandardHugeGraph.java:470) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.backendStoreSystemInfo(StandardHugeGraph.java:249) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:94) ~[hugegraph-dist-0.13.0.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:79) ~[hugegraph-dist-0.13.0.jar:?]
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to access jdbc:mysql://127.0.0.1:3306/?socketTimeout=0&useSSL=false
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:196) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:141) ~[hugegraph-mysql-0.13.0.jar:?]
        ... 14 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_322]
        at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_322]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.connect(MysqlSessions.java:291) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:141) ~[hugegraph-mysql-0.13.0.jar:?]
        ... 14 more
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_322]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_322]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_322]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_322]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_322]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_322]
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_322]
        at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_322]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.connect(MysqlSessions.java:291) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194) ~[hugegraph-mysql-0.13.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:141) ~[hugegraph-mysql-0.13.0.jar:?]
        ... 14 more
```

**Comment by javeme** [comment]
`Connection refused` It seems that the address cannot be connected, please try to check the firewall

**Comment by mklzl** [comment]
I configured 192.168.1.241, but initialized the connection to 127.0.0.1

**Comment by mklzl** [comment]
> `Connection refused` It seems that the address cannot be connected, please try to check the firewall

There is no problem with the network

**Comment by javeme** [comment]
please also config `jdbc.url` option

**Comment by mklzl** [comment]
> 

🆗
