### ISSUE TITLE
[Question] start hugegraph-server error

### ISSUE THREAD

**Issue by mklzl** [apache/incubator-hugegraph#1884]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: 0.13.0
- Backend: palo
- OS: Centos 7.x 

### Your Question (问题描述)

start hugegraph-server:

```bash
/bin/start-hugegraph.sh 
```

```bash
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://192.168.1.241:8085/graphs)...............The operation timed out(30s) when attempting to connect to http://192.168.1.241:8085/graphs
See /home/hugegraph/hugegraph/hugegraph-0.13.0/logs/hugegraph-server.log for HugeGraphServer log output.
```

```bash
tail -100f  /home/hugegraph/hugegraph/hugegraph-0.13.0/logs/hugegraph-server.log
```

```bash
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

2022-05-16 13:36:36 [main] [INFO] c.b.h.u.ConfigUtil - Scanning option 'graphs' directory './conf/graphs'
2022-05-16 13:36:36 [main] [INFO] c.b.h.d.HugeGremlinServer - Configuring Gremlin Server from /home/hugegraph/hugegraph/hugegraph-0.13.0/conf/gremlin-server.yaml
2022-05-16 13:36:36 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'users-hugegraph' with capacity 10240
2022-05-16 13:36:36 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'users_pwd-hugegraph' with capacity 10240
2022-05-16 13:36:36 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'token-hugegraph' with capacity 10240
2022-05-16 13:36:36 [main] [INFO] o.a.t.g.s.u.DefaultGraphManager - Graph [hugegraph] was successfully configured via [./conf/graphs/hugegraph.properties].
2022-05-16 13:36:36 [main] [INFO] o.a.t.g.s.u.ServerGremlinExecutor - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2022-05-16 13:36:37 [main] [INFO] o.a.t.g.s.u.ServerGremlinExecutor - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.u.ServerGremlinExecutor - Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.o.OpLoader - Adding the standard OpProcessor.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.o.OpLoader - Adding the session OpProcessor.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.o.OpLoader - Adding the traversal OpProcessor.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.GremlinServer - Executing start up LifeCycleHook
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.GremlinServer - Executed once at startup of Gremlin Server.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.GremlinServer - idleConnectionTimeout was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.GremlinServer - keepAliveInterval was set to 0 which resolves to 0 seconds when configuring this value - this feature will be disabled
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.graphbinary-v1.0 with org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0, change order of serialization configuration if this is not desired.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, change order of serialization configuration if this is not desired.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.graphbinary-v1.0 with org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0, change order of serialization configuration if this is not desired.
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - Configured application/vnd.gremlin-v3.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0
2022-05-16 13:36:41 [main] [INFO] o.a.t.g.s.AbstractChannelizer - application/json already has org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 configured - it will not be replaced by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, change order of serialization configuration if this is not desired.
2022-05-16 13:36:41 [gremlin-server-boss-1] [INFO] o.a.t.g.s.GremlinServer - Gremlin Server configured with worker thread pool of 1, gremlin pool of 48 and boss thread pool of 1.
2022-05-16 13:36:41 [gremlin-server-boss-1] [INFO] o.a.t.g.s.GremlinServer - Channel started at port 8182.
2022-05-16 13:36:41 [main] [INFO] c.b.h.s.RestServer - RestServer starting...
2022-05-16 13:36:43 [main] [INFO] c.b.h.u.ConfigUtil - Scanning option 'graphs' directory './conf/graphs'
2022-05-16 13:36:43 [main] [INFO] c.b.h.s.RestServer - Graph 'hugegraph' was successfully configured via './conf/graphs/hugegraph.properties'
2022-05-16 13:36:43 [main] [INFO] c.b.h.b.s.p.PaloStore - Open palo session pool for hugegraph/m
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/?socketTimeout=0&useSSL=false'
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=false&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=true&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'schema-id-hugegraph' with capacity 10000
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.c.Cache - Init RamCache for 'schema-name-hugegraph' with capacity 10000
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.p.PaloStore - Open palo session pool for hugegraph/s
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/?socketTimeout=0&useSSL=false'
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=false&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:44 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=true&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:45 [main] [INFO] c.b.h.b.s.p.PaloStore - Open palo session pool for hugegraph/g
2022-05-16 13:36:45 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/?socketTimeout=0&useSSL=false'
2022-05-16 13:36:45 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=false&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:45 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=true&maxReconnects=3&initialTimeout=3&useSSL=false'
2022-05-16 13:36:45 [main] [INFO] o.c.o.l.Uns - OHC using JNA OS native malloc/free
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.c.Cache - Init LevelCache for 'vertex-hugegraph' with capacity 10000:10000000
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.c.Cache - Init LevelCache for 'edge-hugegraph' with capacity 1000:1000000
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/?socketTimeout=0&useSSL=false'
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:46 [main] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:46 [main] [INFO] o.a.t.g.s.GremlinServer - Shutting down OpProcessor[]
2022-05-16 13:36:46 [main] [INFO] o.a.t.g.s.GremlinServer - Shutting down OpProcessor[session]
2022-05-16 13:36:46 [main] [INFO] o.a.t.g.s.GremlinServer - Shutting down OpProcessor[traversal]
2022-05-16 13:36:46 [main] [INFO] o.a.t.g.s.GremlinServer - Shutting down thread pools.
2022-05-16 13:36:46 [gremlin-server-stop] [INFO] o.a.t.g.s.GremlinServer - Executing shutdown LifeCycleHook
2022-05-16 13:36:46 [main] [ERROR] c.b.h.d.HugeGraphServer - HugeRestServer start error: 
com.baidu.hugegraph.backend.BackendException: The backend store of 'hugegraph' has not been initialized
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:369) ~[hugegraph-api-0.13.0.jar:0.69.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:104) ~[hugegraph-api-0.13.0.jar:0.69.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:112) ~[hugegraph-api-0.13.0.jar:0.69.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:49) ~[jersey-server-3.0.3.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:56) ~[jersey-server-3.0.3.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:711) ~[jersey-server-3.0.3.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:330) ~[jersey-container-grizzly2-http-3.0.3.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:376) ~[grizzly-http-server-3.0.1.jar:3.0.1]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:268) ~[grizzly-http-server-3.0.1.jar:3.0.1]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:245) ~[grizzly-http-server-3.0.1.jar:3.0.1]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:68) ~[hugegraph-api-0.13.0.jar:0.69.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:175) ~[hugegraph-api-0.13.0.jar:0.69.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:34) ~[hugegraph-dist-0.13.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:73) ~[hugegraph-dist-0.13.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:121) ~[hugegraph-dist-0.13.0.jar:?]
2022-05-16 13:36:46 [gremlin-server-stop] [INFO] o.a.t.g.s.GremlinServer - Executed once at shutdown of Gremlin Server.
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.HugeGraph - Close graph standardhugegraph[hugegraph]
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:48 [gremlin-server-stop] [INFO] c.b.h.b.s.m.MysqlStore - Connect to the jdbc url: 'jdbc:mysql://192.168.1.241:9036/hugegraph?socketTimeout=0&useSSL=false'
2022-05-16 13:36:54 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/pk/session1-part0
2022-05-16 13:36:54 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=a0122f7d-4882-4474-93ef-960b508c8ca0; Max-Age=86400; Expires=Tue, 17 May 2022 05:36:54 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:36:54 GMT
2022-05-16 13:37:04 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/pk/session2-part0
2022-05-16 13:37:04 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=5d70481e-171e-44a4-91e5-8c1fcb1bb14e; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:04 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:04 GMT
2022-05-16 13:37:14 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/pk/session3-part0
2022-05-16 13:37:14 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=708b7fa8-3ca5-4e2e-94f0-0fe78ffe7874; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:14 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:14 GMT
2022-05-16 13:37:24 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/pk/session4-part0
2022-05-16 13:37:24 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=4c688d6c-b7cf-4c77-ac3d-45a0a05eec29; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:24 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:24 GMT
2022-05-16 13:37:34 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/vl/session2-part0
2022-05-16 13:37:34 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=49a43773-8f7d-43c9-a125-24d78b02b843; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:34 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:34 GMT
2022-05-16 13:37:44 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/vl/session3-part0
2022-05-16 13:37:44 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=1b418b2f-97bb-46da-b47e-e368be668e14; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:44 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:44 GMT
2022-05-16 13:37:54 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/vl/session4-part0
2022-05-16 13:37:54 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=aef2a9d4-b936-40a4-9e90-0114129f3c37; Max-Age=86400; Expires=Tue, 17 May 2022 05:37:54 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:37:54 GMT
2022-05-16 13:38:04 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/il/session3-part0
2022-05-16 13:38:04 [Timer-0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=2c4bbae2-ec4b-4970-95ba-c448d8a532a7; Max-Age=86400; Expires=Tue, 17 May 2022 05:38:04 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:38:04 GMT
2022-05-16 13:38:14 [Timer-0] [INFO] c.b.h.b.s.p.PaloStore - Ready to load one batch from file: ./palo-data/el/session4-part0
Exception in thread "main" 0] [WARN] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "set-cookie: STARROCKS_SESSION_ID=aa49f22d-df65-456a-bb64-38851c1f509a; Max-Age=86400; Expires=Tue, 17 May 2022 05:38:14 GMT". Invalid 'expires' attribute: Tue, 17 May 2022 05:38:14 GMT
2022-05-16 13:38:18 [gremlin-server-stop] [WARN] o.a.t.g.s.GremlinServer - Exception while closing Graph instance [hugegraph]
java.lang.IllegalStateException: Ensure tx closed in all threads when closing graph 'hugegraph'
        at com.google.common.base.Preconditions.checkState(Preconditions.java:531) ~[guava-25.1-jre.jar:?]
        at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-2.1.2.jar:2.1.2.0]
        at com.baidu.hugegraph.StandardHugeGraph.close(StandardHugeGraph.java:904) ~[hugegraph-core-0.13.0.jar:0.13.0.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$7(GremlinServer.java:307) ~[gremlin-server-3.5.1.jar:3.5.1]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_131]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$8(GremlinServer.java:304) ~[gremlin-server-3.5.1.jar:3.5.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2022-05-16 13:38:18 [gremlin-server-stop] [INFO] o.a.t.g.s.GremlinServer - Closed Graph instance [hugegraph]
2022-05-16 13:38:18 [gremlin-server-stop] [INFO] o.a.t.g.s.GremlinServer - Gremlin Server - shutdown complete
2022-05-16 13:38:18 [main] [INFO] c.b.h.HugeGraph - HugeFactory shutdown
com.baidu.hugegraph.backend.BackendException: The backend store of 'hugegraph' has not been initialized
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:369)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:104)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:112)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:49)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:56)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:711)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:330)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:376)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:268)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:245)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:68)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:175)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:34)
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:73)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:121)


### Vertex/Edge example (问题点 / 边数据举例)

_No response_

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

_No response_

**Comment by simon824** [comment]
hi, try this before start hugegraph-server
```shell
bin/init-store.sh
```

**Comment by mklzl** [comment]
> 

I have run start-hugegraph.sh  after init-store.sh

**Comment by mklzl** [comment]
I can find something in Palo called the hugegraph Database

**Comment by mklzl** [comment]
> 

Maybe my version of Palo is too high

**Comment by Awenisme** [comment]
我出现了一样的问题，请问您是如何解决的~感谢
