### ISSUE TITLE
Failed to update counters with type 'SYS_SCHEMA'

### ISSUE THREAD

**Issue by HumanHero** [apache/incubator-hugegraph#1889]
### Bug Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.13.0
- Backend: Postgresql 9.2.24
- OS: 2 CPUs, 16 G RAM, Centos 7.9 

### Expected & Actual behavior (期望与实际表现)

init-store.sh
报错内容如下：
```
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to update counters with type 'SYS_SCHEMA'
	at com.baidu.hugegraph.backend.store.postgresql.PostgresqlTables$Counters.increaseCounter(PostgresqlTables.java:101)
	at com.baidu.hugegraph.backend.store.postgresql.PostgresqlStoreProvider$PostgresqlSchemaStore.increaseCounter(PostgresqlStoreProvider.java:105)
	at com.baidu.hugegraph.backend.store.BackendStore.setCounterLowest(BackendStore.java:111)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.setNextIdLowest(SchemaTransaction.java:565)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:53)
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.initSystemInfo(AbstractBackendStoreProvider.java:150)
	at com.baidu.hugegraph.StandardHugeGraph.initBackend(StandardHugeGraph.java:328)
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:113)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:101)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:79)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 59
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.execute(MysqlSessions.java:521)
	at com.baidu.hugegraph.backend.store.postgresql.PostgresqlTables$Counters.increaseCounter(PostgresqlTables.java:99)
	... 9 more
```

**Comment by javeme** [comment]
@HumanHero 感谢反馈，错误信息看起来是Postgresql环境变化导致的语句不兼容，请问使用的Postgresql版本是什么呢？另外能否增加日志打印一下出错时候的SQL。

**Comment by HumanHero** [comment]
@javeme Postgresql 版本: 9.2.24
报错位置：
com.baidu.hugegraph.backend.store.postgresql.PostgresqlTables$Counters.increaseCounter(PostgresqlTables.java:99)

**Comment by javeme** [comment]
@HumanHero 建议尝试一下 9.6 版本。如果依然有问题，建议打印一下出错时候的SQL语句。

**Comment by HumanHero** [comment]
@javeme 多谢，换用 Postgres 14.3 没问题了。
