### ISSUE TITLE
Failed to load, cause: The primary keys of the table 'xxx' shouldn't be empty

### ISSUE THREAD

**Issue by homealim2012** [apache/incubator-hugegraph#1912]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB, SSD 

### Your Question (问题描述)

Failed to load, cause: The primary keys of the table 'xxx' shouldn't be empty

2022-06-30 12:11:10 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Prepare to clear the data of graph 'hugegraph'
2022-06-30 12:11:15 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - The graph 'hugegraph' has been cleared successfully
2022-06-30 12:11:58 [main] [INFO ] c.b.h.l.r.j.RowFetcher [] - Connect to database jdbc:mysql://127.0.0.1:3306/xxx?useSSL=false&characterEncoding=UTF-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=true
2022-06-30 12:11:59 [main] [ERROR] c.b.h.l.u.Printer [] - Failed to load, cause: The primary keys of the table 'xxx' shouldn't be empty
java.lang.IllegalArgumentException: The primary keys of the table 'xxx' shouldn't be empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[guava-29.0-jre.jar:?]
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
        at com.baidu.hugegraph.loader.reader.jdbc.RowFetcher.readPrimaryKey(RowFetcher.java:112) ~[hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.reader.jdbc.JDBCReader.init(JDBCReader.java:64) ~[hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.loadStructs(HugeGraphLoader.java:217) ~[hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:201) ~[hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:173) ~[hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:110) [hugegraph-loader-0.12.0.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:73) [hugegraph-loader-0.12.0.jar:?]
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.t.TaskManager [] - Waiting for the insert tasks to finish
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.t.TaskManager [] - All the insert tasks finished
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.t.TaskManager [] - The batch-mode tasks service executor shutdown
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.t.TaskManager [] - The single-mode tasks service executor shutdown
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.e.LoadContext [] - Close all failure loggers successfully
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.e.LoadContext [] - Write load progress successfully
2022-06-30 12:11:59 [main] [INFO ] c.b.h.l.e.LoadContext [] - Close HugeClient successfully

**Comment by zhoney** [comment]
@Linary 这块当时有什么考虑吗？逻辑上看起来即使pri字段为空，也不影响后续的从sql数据库导入数据
