### ISSUE TITLE
使用ScyllaDB做后端存储

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1933]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

你好，我想请问一下，就是我用Scylladb做后端存储时，gremlin-server.yaml这个graphs里面不能写图的键值对，写了就启动不了不知道怎么回事？
graphs里面是空的可以初始化，也可以启动，但这样的话就没有图了呀，可以手动调接口创建？
给值就启动不了
给值：
graphs: {
    hugegraph: conf/graphs/hugegraph.properties
}
给值报错：Exception in thread "main" java.lang.IllegalArgumentException: Don't allow to fill value for 'graphs' node in config file '/root/hugegraph/hugegraph-0.12.0/conf/gremlin-server.yaml'
 at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163)
 at com.baidu.hugegraph.util.E.checkArgument(E.java:56)
 at com.baidu.hugegraph.util.ConfigUtil.checkGremlinConfig(ConfigUtil.java:67)
 at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:53)
 at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119)

**Comment by 2867021781** [comment]
> ### Problem Type (问题类型)
> _No response_
> 
> ### Before submit
> * [x]  我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题
> 
> ### Environment (环境信息)
> * Server Version: v0.12.x
> * Backend: RocksDB x nodes, HDD or SSD
> * OS: xx CPUs, xx G RAM, Centos 7.x
> * Data Size:  xx vertices, xx edges
> 
> ### Your Question (问题描述)
> 你好，我想请问一下，就是我用Scylladb做后端存储时，gremlin-server.yaml这个graphs里面不能写图的键值对，写了就启动不了不知道怎么回事？ graphs里面是空的可以初始化，也可以启动，但这样的话就没有图了呀，可以手动调接口创建？ 给值就启动不了 给值： graphs: { hugegraph: conf/graphs/hugegraph.properties } 给值报错：Exception in thread "main" java.lang.IllegalArgumentException: Don't allow to fill value for 'graphs' node in config file '/root/hugegraph/hugegraph-0.12.0/conf/gremlin-server.yaml' at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163) at com.baidu.hugegraph.util.E.checkArgument(E.java:56) at com.baidu.hugegraph.util.ConfigUtil.checkGremlinConfig(ConfigUtil.java:67) at com.baidu.hugegraph.dist.HugeGraphServer.(HugeGraphServer.java:53) at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:119)
> 
> ### Vertex/Edge example (问题点 / 边数据举例)
> _No response_
> 
> ### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)
> _No response_
