### ISSUE TITLE
使用ScyllaDB存储时没有图

### ISSUE THREAD

**Issue by 2867021781** [apache/incubator-hugegraph#1934]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

在使用ScyllaDB做后端存储时，初始化没报错，启动也没有报错，但没有图是怎么回事啊
调用接口：http://172.30.15.151:8081/graphs  返回：{"graphs":[]}
正常不应该有一个hugegraph的图吗？

**Comment by javeme** [comment]
日志中有错误信息或警告信息吗？

**Comment by 2867021781** [comment]
> 日志中有错误信息或警告信息吗？

没报错信息，是否是需要先在  scyllaDB中先建一个keyspace为 hugegraph才行

**Comment by 2867021781** [comment]
> 日志中有错误信息或警告信息吗？
我看到报错信息了，是因为我开启了raft，不过为啥用ScyllaDB不能开启raft呢？

错误信息：Caused by: java.lang.IllegalArgumentException: Can't enable raft mode with scylladb backend
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163) ~[guava-25.1-jre.jar:?]
	at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.backend.store.raft.RaftBackendStoreProvider.checkNonSharedStore(RaftBackendStoreProvider.java:79) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.store.raft.RaftBackendStoreProvider.loadSystemStore(RaftBackendStoreProvider.java:128) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.loadSystemStore(StandardHugeGraph.java:460) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.access$1300(StandardHugeGraph.java:112) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph$StandardHugeGraphParams.loadSystemStore(StandardHugeGraph.java:1178) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.task.ServerInfoManager.listenChanges(ServerInfoManager.java:109) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.task.ServerInfoManager.<init>(ServerInfoManager.java:85) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.task.StandardTaskScheduler.<init>(StandardTaskScheduler.java:106) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.task.TaskManager.addScheduler(TaskManager.java:91) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:217) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:82) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:63) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
	... 18 more
2022-07-20 13:41:21 [main] [INFO] c.b.h.r.RpcServer - RpcServer config is empty, skip starting RpcServer
2022-07-20 13:41:21 [main] [INFO] c.b.h.s.RestServer - The maximum batch writing threads is 12 (total threads 16)
2022-07-20 13:41:21 [main] [INFO] c.b.h.s.RestServer - RestServer started
2022-07-20 13:44:09 [main] [INFO] c.b.h.u.ConfigUtil - Scaning option 'graphs' directory './conf/graphs'
2022-07-20 13:44:09 [main] [INFO] c.b.h.c.InitStore - Init graph with config file: ./conf/graphs/hugegraph.properties
2022-07-20 13:44:11 [main] [INFO] o.c.o.l.Uns - OHC using JNA OS native malloc/free
2022-07-20 13:44:11 [main] [INFO] c.b.h.c.InitStore - Skip init-store due to the backend store of 'hugegraph' had been initialized
2022-07-20 13:44:11 [main] [INFO] c.b.h.HugeGraph - Close graph standardhugegraph[hugegraph]

**Comment by javeme** [comment]
> 不过为啥用ScyllaDB不能开启raft呢？

启用`raft.mode=true`是在RocksDB等非共享存储的场景用于同步数据，ScyllaDB本身是共享存储无需Raft同步数据。

**Comment by 2867021781** [comment]
> > 不过为啥用ScyllaDB不能开启raft呢？
> 
> 启用`raft.mode=true`是在RocksDB等非共享存储的场景用于同步数据，ScyllaDB本身是共享存储无需Raft同步数据。

好的了解，但是在使用gremlin语句查询时出现了问题： 工具：hugegraph-hubble   
语句：g.V() 
错误：Error encountered evaluating script: g.V('1:42Qna','1:42_ij','1:446rx',...').bothE().dedup().limit(500)
语句：g.V("1:1K").repeat(out()).until(out().count().is(0)).path() 
错误：Error encountered evaluating script: g.V('1:42YLy','1:42xIs',...').bothE().local(limit(100)).dedup()

数据量：vertices/edges 1134890/2987624
是因为返回的数据有条数限制吗？我用rocksdb或者hbase是可以查询出来的

**Comment by javeme** [comment]
可能是超时了，可以尝试如下语句减少渲染探测数据：
g.V("1:1K").repeat(outE().inV().simplePath()).until(outE().count().is(0)).path()

或者尝试调大超时时间：
https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915

**Comment by 2867021781** [comment]
> 

换你的那个可以执行成功，但是g.V()还是不行，而且是立马返回错误的，不像超时，超时应该有个timeout

**Comment by 2867021781** [comment]
> 可能是超时了，可以尝试如下语句减少渲染探测数据： `g.V("1:1K").repeat(outE().inV().simplePath()).until(outE().count().is(0)).path() ` 或者尝试调大超时时间： [#1429 (comment)](https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915)

换你的那个可以执行成功，但是g.V()还是不行，而且是立马返回错误的，不像超时，超时应该有个timeout

**Comment by 2867021781** [comment]
> > 可能是超时了，可以尝试如下语句减少渲染探测数据： `g.V("1:1K").repeat(outE().inV().simplePath()).until(outE().count().is(0)).path() ` 或者尝试调大超时时间： [#1429 (comment)](https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915)
> 
> 换你的那个可以执行成功，但是g.V()还是不行，而且是立马返回错误的，不像超时，超时应该有个timeout

使用g.E()是没有问题的

**Comment by 2867021781** [comment]
> > 可能是超时了，可以尝试如下语句减少渲染探测数据： `g.V("1:1K").repeat(outE().inV().simplePath()).until(outE().count().is(0)).path() ` 或者尝试调大超时时间： [#1429 (comment)](https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915)
> 
> 换你的那个可以执行成功，但是g.V()还是不行，而且是立马返回错误的，不像超时，超时应该有个timeout

使用g.E()是没有问题的

**Comment by 2867021781** [comment]
> > 可能是超时了，可以尝试如下语句减少渲染探测数据： `g.V("1:1K").repeat(outE().inV().simplePath()).until(outE().count().is(0)).path() ` 或者尝试调大超时时间： [#1429 (comment)](https://github.com/apache/incubator-hugegraph/issues/1429#issuecomment-1041203915)
> 
> 换你的那个可以执行成功，但是g.V()还是不行，而且是立马返回错误的，不像超时，超时应该有个timeout

使用g.E()是可以的 ，然后使用g.V().count()得到的数量也跟导入的不一致，导入没有报错

**Comment by javeme** [comment]
立马返回错误的有详细的错误信息吗？

**Comment by 2867021781** [comment]
> 立马返回错误的有详细的错误信息吗？
hugegraph最新版本，hugegraph集群，后端使用scylladb集群
在hugegraph-hubble上操作
命令：g.V()
返回：2022-07-21 20:23:11.235 ERROR 8849 --- [http-nio-0.0.0.0-9090-exec-2] c.b.h.handler.MessageSourceHandler       : There is no message for key 'Error encountered evaluating script: g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)'

另外，在大数据量的情况下 g.V().count()会出现两次返回结果不一致情况（随机，但出现此现象很频繁），g.E().count()也是这样

**Comment by 2867021781** [comment]
> 立马返回错误的有详细的错误信息吗？

hugegraph最新版本，hugegraph集群，后端使用scylladb集群
在hugegraph-hubble上操作
命令：g.V()
返回：2022-07-21 20:23:11.235 ERROR 8849 --- [http-nio-0.0.0.0-9090-exec-2] c.b.h.handler.MessageSourceHandler : There is no message for key 'Error encountered evaluating script: g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)'

另外，在大数据量的情况下 g.V().count()会出现两次返回结果不一致情况（随机，但出现此现象很频繁），g.E().count()也是这样

**Comment by javeme** [comment]
可以尝试不在hubble中执行，而是直接发送到Server执行报错Gremlin语句（可参考 [gremlin api](https://hugegraph.apache.org/docs/clients/restful-api/gremlin/)），看看报错信息，包括服务端的错误日志信息：
`g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)`

只有ScyllaDB存储会出现结果不一致的情况吗？

**Comment by 2867021781** [comment]
> 可以尝试不在hubble中执行，而是直接发送到Server执行报错Gremlin语句（可参考 [gremlin api](https://hugegraph.apache.org/docs/clients/restful-api/gremlin/)），看看报错信息，包括服务端的错误日志信息： `g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)`
> 
> 只有ScyllaDB存储会出现结果不一致的情况吗？

1、是的，结果不一致只在scyllaDB中看到了，而且是百万顶点边的情况下；
2、g.V()的报错在Scylladb和cockroachdb集群都出现了，跟数据量没有关系，无论数据大小都会报错，我尝试直接发送到server试一下

**Comment by 2867021781** [comment]
> 可以尝试不在hubble中执行，而是直接发送到Server执行报错Gremlin语句（可参考 [gremlin api](https://hugegraph.apache.org/docs/clients/restful-api/gremlin/)），看看报错信息，包括服务端的错误日志信息： `g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)`
> 
> 只有ScyllaDB存储会出现结果不一致的情况吗？

1、使用http://172.30.15.151:8081/gremlin?gremlin=hugegraph.traversal().V()接口直接访问是可以返回数据的，Hubble上不行（hubble版本1.6.0，server 0.12.0）；
2、count()结果不一致现在又复现不了了，等后面再看看是否还会出现这种情况

**Comment by javeme** [comment]
这个Gremlin语句直接发送到Server执行可以吗：
`g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)`

**Comment by 2867021781** [comment]
> 这个Gremlin语句直接发送到Server执行可以吗： `g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)`

执行http://172.30.15.151:8081/gremlin?gremlin=g.V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)，返回{"exception":"groovy.lang.MissingPropertyException","message":"No such property: g for class: Script5","cause":"[groovy.lang.MissingPropertyException]"}

执行http://172.30.15.151:8081/gremlin?gremlin=hugegraph.traversal().V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)，返回{"exception":"java.lang.NullPointerException","message":"Error encountered evaluating script: hugegraph.traversal().V(1,'1:marko',2,'1:josh','1:vadas','1:tom','1:peter','1:li,nary').bothE().dedup().limit(500)","cause":"[java.lang.NullPointerException]"}

**Comment by 2867021781** [comment]
> 第1个错误是预期的，如果没有绑定g变量。 第2个错误，可以在服务端看看详细的错误日志信息吗？

服务端没有报错信息，使用hubble的时候会报错，调用api不会，只有hubble有报错信息，是不是hubble的bug，之前用rocksdb和hbase是没问题的，scylladb,cassandra,cockroachdb都有这个问题:hubble上运行g.V()报错

**Comment by 2867021781** [comment]
> 第1个错误是预期的，如果没有绑定g变量。 第2个错误，可以在服务端看看详细的错误日志信息吗？

你们使用Scylla/Cassandra集群做后端存储的时候，会有这个问题吗？ Hubble和server都是最新版本的

**Comment by javeme** [comment]
我们没有这个问题，请问使用的最新版本是指master版本还是0.12版本呢？如果能提供一些详细的错误日志信息可能更容易找到错误原因。

**Comment by 2867021781** [comment]
> 我们没有这个问题，请问使用的最新版本是指master版本还是0.12版本呢？如果能提供一些详细的错误日志信息可能更容易找到错误原因。

![image](https://user-images.githubusercontent.com/73277908/181402291-74ef0983-c4c5-4024-9253-fa6e76e4ad5c.png)
用的这个，直接在Linux部署的

**Comment by 2867021781** [comment]
> 我们没有这个问题，请问使用的最新版本是指master版本还是0.12版本呢？如果能提供一些详细的错误日志信息可能更容易找到错误原因。

![image](https://user-images.githubusercontent.com/73277908/181402865-3fadb7d8-0cc1-4b12-848e-00c41d440d98.png)
用的这个包，直接在Linux部署的
