### ISSUE TITLE
[Bug] 新下载的server 0.12的包，把restserver.url=http://127.0.0.1:8080改成restserver.url=http://0.0.0.0:8080启动会报错

### ISSUE THREAD

**Issue by xxyp** [apache/incubator-hugegraph#1992]
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB 
Centos 7
java 8

### Expected & Actual behavior (期望与实际表现)

报错信息：
[gremlin-server-stop] [INFO] c.b.h.HugeGraph - Close graph standardhugegraph[hugegraph]
2022-10-26 08:56:41 [gremlin-server-stop] [WARN] o.a.t.g.s.GremlinServer - Exception while closing Graph instance [hugegraph]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@70b7d1eb rejected from java.util.concurrent.ThreadPoolExecutor@7176e877[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_292]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_292]
        at com.baidu.hugegraph.event.EventHub.notify(EventHub.java:155) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.close(AbstractBackendStoreProvider.java:105) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.close(StandardHugeGraph.java:900) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$7(GremlinServer.java:298) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_292]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$8(GremlinServer.java:295) ~[gremlin-server-3.4.3.jar:3.4

把restserver.url改回http://127.0.0.1:8080，可以正常启动

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
.
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
.
```

**Comment by imbajin** [comment]
你给的报错信息来看似乎没有相关的, 能否重置一下 server 环境.

重新初始一个新的 rocksdb 后端, 然后先修改 ip 为 `0.0.0.0` 然后再启动?
