### ISSUE TITLE
[Bug]  get exception when  connecting to HugeGraph  

### ISSUE THREAD

**Issue by JasonQi2020** [apache/incubator-hugegraph#2040]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: RocksDB x 1,  SSD 
- OS: xx CPUs, 8 G RAM,   centos 7  
- Data Size:  20 vertices, 10 edges 

### Expected & Actual behavior (期望与实际表现)

**the following code complains:**
       
```
 GraphTraversalSource g = traversal().withRemote("\resources\\remote.properties");
  org.apache.tinkerpop.gremlin.structure.Vertex next = g.V().next();
 System.out.println(next);
```

****exception**** 

java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException

	at org.apache.tinkerpop.gremlin.process.remote.RemoteConnection.from(RemoteConnection.java:73)
	at org.apache.tinkerpop.gremlin.process.traversal.AnonymousTraversalSource.withRemote(AnonymousTraversalSource.java:76)
	at org.apache.tinkerpop.gremlin.process.traversal.AnonymousTraversalSource.withRemote(AnonymousTraversalSource.java:66)
	at com.blackwings.hugegraph.dao.HugegraphTest.con3(HugegraphTest.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.tinkerpop.gremlin.process.remote.RemoteConnection.from(RemoteConnection.java:71)
	... 27 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/baidu/hugegraph/io/HugeGraphSONModule.registerCommonSerializers(Lorg/apache/tinkerpop/shaded/jackson/databind/module/SimpleModule;)V @58: invokespecial
  Reason:
    Type 'com/baidu/hugegraph/date/SafeDateFormat' (current frame, stack[5]) is not assignable to 'java/text/DateFormat'
  Current Frame:
    bci: @58
    flags: { }
    locals: { 'org/apache/tinkerpop/shaded/jackson/databind/module/SimpleModule', integer }
    stack: { 'org/apache/tinkerpop/shaded/jackson/databind/module/SimpleModule', 'java/lang/Class', uninitialized 47, uninitialized 47, 'java/lang/Boolean', 'com/baidu/hugegraph/date/SafeDateFormat' }
  Bytecode:
    0000000: 2a12 0fbb 0010 59b7 0011 b600 1257 2a12
    0000010: 13bb 0014 59b7 0015 b600 1257 2a12 16bb
    0000020: 0017 59b7 0018 b600 1257 033c 2a12 19bb
    0000030: 001a 591b b800 1bb2 001c b700 1db6 0012
    0000040: 572a 1219 bb00 1e59 bb00 1e59 b700 1fb2
    0000050: 001c 1220 b700 21b6 0022 572a 1223 bb00
    0000060: 2459 b700 25b6 0012 572a 1223 bb00 2659
    0000070: b700 27b6 0022 572a 1228 bb00 2959 b700
    0000080: 2ab6 0012 572a 1228 bb00 2b59 b700 2cb6
    0000090: 0022 57b1                              

	at com.baidu.hugegraph.io.HugeGraphIoRegistry.<init>(HugeGraphIoRegistry.java:36)
	at com.baidu.hugegraph.io.HugeGraphIoRegistry.<clinit>(HugeGraphIoRegistry.java:27)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1.lambda$configure$0(GraphBinaryMessageSerializerV1.java:108)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1.configure(GraphBinaryMessageSerializerV1.java:106)
	at org.apache.tinkerpop.gremlin.driver.Settings$SerializerSettings.lambda$create$0(Settings.java:425)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.apache.tinkerpop.gremlin.driver.Settings$SerializerSettings.create(Settings.java:425)
	at org.apache.tinkerpop.gremlin.driver.Cluster.getBuilderFromSettings(Cluster.java:224)
	at org.apache.tinkerpop.gremlin.driver.Cluster.build(Cluster.java:172)
	at org.apache.tinkerpop.gremlin.driver.Cluster.open(Cluster.java:260)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection.<init>(DriverRemoteConnection.java:80)
	... 32 more

configration file : 

**remote.properties**

gremlin.remote.remoteConnectionClass=org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
gremlin.remote.driver.clusterFile=remote-objects.yaml
gremlin.remote.driver.sourceName=g

**remote-objects.yaml**

hosts: [1.320.5.220]
port: 8182
serializer: {
  className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
  config: {
    ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }
}

**Comment by javeme** [comment]
可以参考下类似问题：
- https://github.com/apache/incubator-hugegraph/issues/1871#issuecomment-1125808166
- https://github.com/apache/incubator-hugegraph/issues/1785#issuecomment-1072384009
- https://github.com/apache/incubator-hugegraph/issues/1501#issuecomment-862022028

**Comment by JasonQi2020** [comment]
Thanks for your answer. 
I tried to follow the solutions that you recommended , but unfortunately  it still doesn't work. 

could you please share the version of gremlin and thinkpop  in POM.xml   with me ?  
I am using the  3.5.2.  
        <dependency>
            <groupId>com.baidu.hugegraph</groupId>
            <artifactId>hugegraph-core</artifactId>
            <version>0.11.2</version>
        </dependency>


        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-core</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>tinkergraph-gremlin</artifactId>
            <version>3.5.2</version>
        </dependency>

            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-driver</artifactId>
            <version>3.5.2</version>
            <scope>test</scope>
        </dependency>

Thanks.
