### ISSUE TITLE
部署的服务端版本号为1.0.0，客户端的版本号为（hugegraph-client）2.0.1，启动时客户端时报The version 0.69.0.0 of 'hugegraph-api in server' is not in [0.38, 0.68)，请问客户端的最新版本是多少？

### ISSUE THREAD

**Issue by hh516554097** [apache/incubator-hugegraph#2102]
### Problem Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v1.0.0
- Backend: HBase
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Caused by: java.lang.IllegalStateException: The version 0.69.0.0 of 'hugegraph-api in server' is not in [0.38, 0.68)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:532) ~[guava-29.0-jre.jar:na]
	at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.util.VersionUtil.check(VersionUtil.java:65) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:112) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:95) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:67) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:67) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.bme.hugegraph.config.HugeGraphClient.hugeClient5(HugeGraphClient.java:33) ~[classes/:na]
	at com.bme.hugegraph.config.HugeGraphClient$$EnhancerBySpringCGLIB$$e6056aea.CGLIB$hugeClient5$1(<generated>) ~[classes/:na]

**Comment by imbajin** [comment]
感谢反馈, 虽然这个问题应该在 toolchain 仓库提, 不过因为切换到 `Apache` 的第一个新版本之后大家容易遇到这样的困惑, 后面发版文档和 `README` 中都会进行更新, 显著标明

目前可参考: (注意需要 xml 配置里也加上一个配置, 正式 release 之后就不需要了)
- https://github.com/apache/incubator-hugegraph-toolchain/issues/410#issuecomment-1373379398
- https://github.com/apache/incubator-hugegraph-toolchain#maven-dependencies
