### ISSUE TITLE
【client连接失败】hugegraph-client连接图库报错：class not found jakarta.ws.rs.ProcessingException

### ISSUE THREAD

**Issue by dongma** [apache/incubator-hugegraph#2259]
### Bug Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

图库的版本为Release 1.0.0，java client的版本为：org.apache.hugegraph:hugegraph-client:1.0.0。
问题：跑图库连接时，报class Not found：jakarta.ws.rs.ProcessingException
添加了：jakarta.ws.rs-api: 3.0.0依赖后，重新执行又提示其他类 not found
javax.ws.rs.core.Configurable

### Expected & Actual behavior (期望与实际表现)

2023-07-27 21:00:47.841  INFO 27734 --- [           main] org.apache.huge.HugegraphApp             : Starting HugegraphApp with PID 27734 (hugegraph-client/target/classes started by haizhi in /Users/haizhi/datahub/hugegraph-client)
2023-07-27 21:00:47.871  INFO 27734 --- [           main] org.apache.huge.HugegraphApp             : No active profile set, falling back to default profiles: default
2023-07-27 21:00:48.980  INFO 27734 --- [           main] org.apache.huge.HugegraphApp             : Started HugegraphApp in 2.084 seconds (JVM running for 3.806)
2023-07-27 21:00:49.761  INFO 27734 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-07-27 21:00:49.788 ERROR 27734 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: jakarta/ws/rs/ProcessingException
	at org.apache.hugegraph.driver.HugeClient.<init>(HugeClient.java:62) ~[hugegraph-client-1.0.0.jar:1.0.0]
	at org.apache.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:62) ~[hugegraph-client-1.0.0.jar:1.0.0]
	at org.apache.huge.HugegraphApp.testGraphConnect(HugegraphApp.java:43) [classes/:na]
	at org.apache.huge.HugegraphApp.run(HugegraphApp.java:35) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.apache.huge.HugegraphApp.main(HugegraphApp.java:30) [classes/:na]
Caused by: java.lang.ClassNotFoundException: jakarta.ws.rs.ProcessingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_202]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_202]
	... 10 common frames omitted

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
@Override
    public void run(String... args) throws Exception {
        testGraphConnect("http://localhost:8080", "hugegraph");
//        officialCase();
    }

    /**
     * 测试图库的连接
     */
    public Boolean testGraphConnect(String server, String graph) {
        HugeClient hugeClient = HugeClient.builder(server, graph).build();
        GraphManager graphManager = hugeClient.graph();
        log.info("hugegraph connect test, server: [{}], metric: [{}]", server,
                graphManager.graph());
        return Objects.isNull(graphManager);
    }
```

**Comment by dongma** [comment]
此问题已解决，完整的pom.xml请参考issue，https://github.com/apache/incubator-hugegraph-toolchain/issues/495
