### ISSUE TITLE
[Bug] hugeclient批量数据写入，提示：java.lang.illegalArgumentException: the max length of bytes is 65535, but get 337492.

### ISSUE THREAD

**Issue by dongma** [apache/incubator-hugegraph#2291]
### Bug Type (问题类型)

rest-api (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

图库版本：1.0.0版本
存储引擎：HBase
数据量：点1亿+，边数量1亿+。点已正常写入，边上有属性字段较多，一批次写入1000条左右。

期望，请求体大小大于95535，看图库服务端是否参数可调整（限制请求体大小的参数为？）

### Expected & Actual behavior (期望与实际表现)

hugeclient批量数据写入，一批次request body请求次数大于服务端默认的65535大小，导致关系数据无法写入。
异常堆栈如下：
```
java.lang.IllegalArgumentException: the max length of bytes is 65535,  but get 337492.
at org.apache.hugegraph.exception.ServerException.fromResponse(ServerException.java: 45)
at org.apache.hugegraph.client.RestClient.checkStatus(RestClinet.java:91)
at org.apache.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:232)
at org.apache.hugegraph.api.graph.EdgeAPI.create(EdgeAPI.java:58)
at org.apache.hugegraph.driver.GraphManager.addEdges(GraphManager.java:262)
at org.apache.hugegraph.driver.GraphManager.addEdges(GraphManager.java:254)
.....
```

**Comment by imbajin** [comment]
@DanGuge could take a look for it? Better to make the vertex/edge ID length configurable

**Comment by DanGuge** [comment]
> @DanGuge could take a look for it? Better to make the vertex/edge ID length configurable

I will check this later

**Comment by dongma** [comment]
> @DanGuge could take a look for it? Better to make the vertex/edge ID length configurable

Thanks for your reply, I had resolved this problem last night [憨笑] . The reason why failed to write record to hugegraph server is the Text(String) type  property value length was limit to 65535.

After check my data rows, one property value' length of few rows is over that 65535, after limit property length, the write operation is success.  

Below is the full  logic to check property value length :
<img width="1065" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/24204526/f831ff53-a3b0-4e66-aa1c-fab2baec2896">

<img width="821" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/24204526/7e693373-8d79-49d2-998c-613324d6d7fb">

<img width="1049" alt="image" src="https://github.com/apache/incubator-hugegraph/assets/24204526/599f1349-704c-4ebf-884f-5bee6c1ea26f">

**Comment by dongma** [comment]
close my issue, the length Text property value should less than 65535.

**Comment by imbajin** [comment]
> close my issue, the length Text property value should less than 65535.

we know the limitation, and consider add an option for user to modify it (so as the length of vertex/edge ID)

**Comment by LiJie20190102** [comment]
> > close my issue, the length Text property value should less than 65535.
> 
> we know the limitation, and consider add an option for user to modify it (so as the length of vertex/edge ID)

Excuse me, is there a PR solution to this issue

**Comment by imbajin** [comment]
> > > close my issue, the length Text property value should less than 65535.
> > 
> > we know the limitation, and consider add an option for user to modify it (so as the length of vertex/edge ID)
> 
> Excuse me, is there a PR solution to this issue
> 
> 

thanks for the reminder，address it again

**Comment by LiJie20190102** [comment]
I want to implement this function, can it be assigned to me

**Comment by imbajin** [comment]
> I want to implement this function, can it be assigned to me

@LiJie20190102 If u want to config property length, we could reopen this issue & link PR to it
If u only want to config VertexID length, u could submit a new issue (better)

**Comment by dongma** [comment]
> > > close my issue, the length Text property value should less than 65535.
> > 
> > 
> > we know the limitation, and consider add an option for user to modify it (so as the length of vertex/edge ID)
> 
> Excuse me, is there a PR solution to this issue

@LiJie20190102  I currently don't create PR to this repository to fix this problem,  "extract the limitation to a configuration" is the suggesstion from database developers.

**Comment by LiJie20190102** [comment]
> > I want to implement this function, can it be assigned to me
> 
> @LiJie20190102 If u want to config property length, we could reopen this issue & link PR to it If u only want to config VertexID length, u could submit a new issue (better)

I want to do both

**Comment by LiJie20190102** [comment]
I think a good solution is not to limit the length of vertex/edge ID or attributes, but to dynamically change the attribute values of org.apache.hugegraph.backend.serializer.BytesBuffer, such as UINT8_ MAX, because in business use, sometimes the length of vertex IDs does need to be this long. In this case, we should not limit their length, but rather modify the limit to accept the corresponding value，WDYT @imbajin

**Comment by imbajin** [comment]
> I think a good solution is not to limit the length of vertex/edge ID or attributes, but to dynamically change the attribute values of org.apache.hugegraph.backend.serializer.BytesBuffer, such as UINT8_ MAX, because in business use, sometimes the length of vertex IDs does need to be this long. In this case, we should not limit their length, but rather modify the limit to accept the corresponding value，WDYT @imbajin @dongma

`var-length` occupation generally affects **read and write** performance, including but not limited to the impact of `EID` **filling occupation** and scanning properties. It would be more appropriate to consider allowing users to **customize configurations** first? (then we could try to test the var-length way)



@dosu-bot What's your suggestion/analysis?
