### ISSUE TITLE
[Question] 配置的是pgsql，为什么连接用mysql，连接失败

### ISSUE THREAD

**Issue by liming1010** [apache/incubator-hugegraph#2549]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

centos9
hugegraph 1.3

### Your Question (问题描述)

```
Initializing HugeGraph Store...
2024-06-04 11:14:56 [main] [INFO] o.a.h.u.ConfigUtil - Scanning option 'graphs' directory './conf/graphs'
2024-06-04 11:14:56 [main] [INFO] o.a.h.c.InitStore - Init graph with config file: ./conf/graphs/hugegraph.properties
2024-06-04 11:14:57 [main] [INFO] o.a.h.b.s.m.MysqlSessions - Connect to the jdbc url: 'jdbc:postgresql://192.168.105.187:5432/core?currentSchema=hugegraph&loggerLevel=OFF&socketTimeout=0&useSSL=false'
Exception in thread "main" java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.apache.hugegraph.HugeFactory]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:84)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:72)
        at org.apache.hugegraph.cmd.InitStore.initGraph(InitStore.java:96)
        at org.apache.hugegraph.cmd.InitStore.main(InitStore.java:80)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:80)
        ... 3 more
Caused by: org.apache.hugegraph.HugeException: Failed to open schema transaction
        at org.apache.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:467)
        at org.apache.hugegraph.StandardHugeGraph.access$2700(StandardHugeGraph.java:121)
        at org.apache.hugegraph.StandardHugeGraph$TinkerPopTransaction.getOrNewTransaction(StandardHugeGraph.java:1475)
        at org.apache.hugegraph.StandardHugeGraph$TinkerPopTransaction.doOpen(StandardHugeGraph.java:1384)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.open(AbstractTransaction.java:95)
        at org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:213)
        at org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:210)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractThreadLocalTransaction.doReadWrite(AbstractThreadLocalTransaction.java:92)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.readWrite(AbstractTransaction.java:136)
        at org.apache.hugegraph.StandardHugeGraph.graphTransaction(StandardHugeGraph.java:537)
        at org.apache.hugegraph.StandardHugeGraph.backendStoreFeatures(StandardHugeGraph.java:266)
        at org.apache.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:226)
        at org.apache.hugegraph.HugeFactory.open(HugeFactory.java:88)
        at org.apache.hugegraph.HugeFactory.open(HugeFactory.java:66)
        ... 8 more
Caused by: org.apache.hugegraph.backend.BackendException: Failed to obtain database info
        at org.apache.hugegraph.backend.store.postgresql.PostgresqlSessions.existsDatabase(PostgresqlSessions.java:58)
        at org.apache.hugegraph.backend.store.mysql.MysqlStore.open(MysqlStore.java:119)
        at org.apache.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:80)
        at org.apache.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:28)
        at org.apache.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:79)
        at org.apache.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54)
        at org.apache.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:463)
        ... 21 more
Caused by: org.apache.hugegraph.backend.BackendException: Failed to access jdbc:postgresql://192.168.105.187:5432/core?currentSchema=hugegraph&loggerLevel=OFF&socketTimeout=0&useSSL=false
        at org.apache.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194)
        at org.apache.hugegraph.backend.store.postgresql.PostgresqlSessions.existsDatabase(PostgresqlSessions.java:54)
        ... 27 more
Caused by: org.postgresql.util.PSQLException: 尝试连线已失败。
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
        at org.postgresql.Driver.makeConnection(Driver.java:434)
        at org.postgresql.Driver.connect(Driver.java:291)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at org.apache.hugegraph.backend.store.mysql.MysqlSessions.connect(MysqlSessions.java:291)
        at org.apache.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:192)
        ... 28 more
```

配置是pgsql
但是出现了org.apache.hugegraph.backend.store.mysql.MysqlStore.open(MysqlStore.java:119) ~[hugegraph-mysql-1.3.0.jar:1.3.0]
是不是这个问题导致的连接失败

**Comment by liming1010** [comment]
已经连接上了，有个新问题
```
2024-06-04 11:31:34 [main] [INFO] o.c.o.l.Uns - OHC using JNA OS native malloc/free
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.c.CacheManager - Init LevelCache for 'vertex-hugegraph' with capacity 10000:10000000
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.c.CacheManager - Init LevelCache for 'edge-hugegraph' with capacity 1000:1000000
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.c.CacheManager - Init RamCache for 'users-hugegraph' with capacity 10240
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.c.CacheManager - Init RamCache for 'users_pwd-hugegraph' with capacity 10240
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.c.CacheManager - Init RamCache for 'token-hugegraph' with capacity 10240
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.s.m.MysqlSessions - Connect to the jdbc url: 'jdbc:postgresql://192.168.105.187:5432/core?currentSchema=hugegraph&loggerLevel=OFF&socketTimeout=0&useSSL=false'
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.s.m.MysqlSessions - Connect to the jdbc url: 'jdbc:postgresql://192.168.105.187:5432/core?currentSchema=hugegraph&loggerLevel=OFF&socketTimeout=0&useSSL=false'
2024-06-04 11:31:34 [main] [INFO] o.a.h.b.s.m.MysqlSessions - Connect to the jdbc url: 'jdbc:postgresql://192.168.105.187:5432/hugegraph?loggerLevel=OFF&characterEncoding=utf-8&rewriteBatchedStatements=true&useServerPrepStmts=false&autoReconnect=true&maxReconnects=3&initialTimeout=3&useSSL=false'
2024-06-04 11:31:34 [main] [INFO] o.a.h.StandardHugeGraph - Close graph standardhugegraph[hugegraph]
Exception in thread "main" org.apache.hugegraph.backend.BackendException: Failed to connect database 'hugegraph'
        at org.apache.hugegraph.backend.store.mysql.MysqlStore.init(MysqlStore.java:169)
        at org.apache.hugegraph.backend.store.postgresql.PostgresqlStoreProvider$PostgresqlSystemStore.init(PostgresqlStoreProvider.java:198)
        at org.apache.hugegraph.backend.store.AbstractBackendStoreProvider.init(AbstractBackendStoreProvider.java:117)
        at org.apache.hugegraph.StandardHugeGraph.initBackend(StandardHugeGraph.java:361)
        at org.apache.hugegraph.cmd.InitStore.initBackend(InitStore.java:125)
        at org.apache.hugegraph.cmd.InitStore.initGraph(InitStore.java:110)
        at org.apache.hugegraph.cmd.InitStore.main(InitStore.java:80)2024-06-04 11:31:34 [main] [INFO] o.a.h.HugeFactory - HugeFactory shutdown
```
指定了数据库jdbc:postgresql://192.168.105.187:5432/core?currentSchema=hugegraph，为什么jdbc:postgresql://192.168.105.187:5432/hugegraph有变成了这个了？

这是我的配置
```
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://192.168.105.187:5432/
jdbc.username=
jdbc.password=
jdbc.postgresql.connect_database=core?currentSchema=hugegraph
```

**Comment by liming1010** [comment]
说的很详细了，谢谢
