### ISSUE TITLE
[Question] How to disable legacy master-worker mechanism in multi-server

### ISSUE THREAD

**Issue by shirleyStorage** [apache/incubator-hugegraph#2667]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.0.0 (Apache Release Version)
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

How to disable legacy master-worker mechanism in multi-server

**Comment by imbajin** [comment]
> To disable the legacy master-worker mechanism in a multi-server setup using Apache HugeGraph, you need to set the `server.role` configuration option to "computer". This can be done in your configuration file as follows:
> 
> ```ini
> server.role=computer
> ```
> 
> This setting ensures that the `RoleElectionStateMachine` is not initialized, effectively disabling the legacy master-worker mechanism. Here is the relevant configuration option:
> 
> ```java
> public static final ConfigOption<String> SERVER_ROLE =
>         new ConfigOption<>(
>                 "server.role",
>                 "The role of nodes in the cluster, available types are " +
>                 "[master, worker, computer]",
>                 allowValues("master", "worker", "computer"),
>                 "master"
>         );
> ```
> 
> By setting `server.role` to "computer", the `supportRoleElection` will be false, and the role state machine will not be initialized [[1]](https://github.com/apache/incubator-hugegraph/blob/master/hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/config/ServerOptions.java?rgh-link-date=2024-09-22T06%3A49%3A54Z)[[2]](https://github.com/apache/incubator-hugegraph/blob/master/hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/core/GraphManager.java?rgh-link-date=2024-09-22T06%3A49%3A54Z).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu Thanks for the direct solution, could u also provide more details about the legacy master-worker role code design & usage (As detailed and systematic as possible)?

**Comment by shirleyStorage** [comment]
@dosu What do the three server.role configurations mean？

**Comment by shirleyStorage** [comment]
@dosu How would you start a minimal cluster with each of the three server.role values?

**Comment by shirleyStorage** [comment]
@dosu How to start a single cluster with backend=rocksdb？

**Comment by shirleyStorage** [comment]
@dosu What is the recommended jdk version for compiling hugegraph?

**Comment by shirleyStorage** [comment]
@dosu How to run standalone mode in docker after hugegraph is built locally?

**Comment by shirleyStorage** [comment]
@dosu Why use hugegraph-pd instead of hugegraph-server?

**Comment by shirleyStorage** [comment]
@dosu But I only need hugegraph server to run standalone hugegraph cluster locally?

**Comment by shirleyStorage** [comment]
@dosu How do I make a hugegraph/hugegraph docker image from my own hugegraph source code？

**Comment by shirleyStorage** [comment]
@dosu How do I make a hugegraph/hugegraph docker image from my own hugegraph source code？only for backend=rocksdb and start a  standalone cluster

**Comment by shirleyStorage** [comment]
@dosu I ran into the following problem when restarting container after compiling with the latest master branch code:
```
java.lang.IllegalArgumentException: The server with name 'server-1' already in cluster
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:167) ~[guava-31.0.1-android.jar:?]
	at org.apache.hugegraph.util.E.checkArgument(E.java:52) ~[hugegraph-common-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.task.ServerInfoManager.initServerInfo(ServerInfoManager.java:110) ~[hugegraph-core-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.StandardHugeGraph.serverStarted(StandardHugeGraph.java:288) ~[hugegraph-core-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.core.GraphManager.serverStarted(GraphManager.java:484) ~[hugegraph-api-1.5.0.jar:0.71.0.0]
	at org.apache.hugegraph.core.GraphManager.init(GraphManager.java:125) ~[hugegraph-api-1.5.0.jar:0.71.0.0]
	at org.apache.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:143) ~[hugegraph-api-1.5.0.jar:0.71.0.0]
	at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:49) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:56) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:711) ~[jersey-server-3.0.3.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:330) ~[jersey-container-grizzly2-http-3.0.3.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:376) ~[grizzly-http-server-3.0.1.jar:3.0.1]
	at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:268) ~[grizzly-http-server-3.0.1.jar:3.0.1]
	at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:245) ~[grizzly-http-server-3.0.1.jar:3.0.1]
	at org.apache.hugegraph.server.RestServer.start(RestServer.java:70) ~[hugegraph-api-1.5.0.jar:0.71.0.0]
	at org.apache.hugegraph.server.RestServer.start(RestServer.java:177) ~[hugegraph-api-1.5.0.jar:0.71.0.0]
	at org.apache.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:31) ~[hugegraph-dist-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:60) ~[hugegraph-dist-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:120) ~[hugegraph-dist-1.5.0.jar:1.5.0]
```

**Comment by shirleyStorage** [comment]
@dosu If the server is killed suddenly. How to execute removeSelfServerInfo? This ServerInfo will always be there?

**Comment by shirleyStorage** [comment]
@dosu 
docker run a 'backend=rocksdb ,standalone' cluster
1. The first time I started properly, the service worked. 
2. docker restart hugegraph-Container, error message: The server with name 'server-1' already in cluster. 
3. Run docker restart hugegraph-Container again, the service starts normally again. What is the reason?

**Comment by shirleyStorage** [comment]
@dosu Can you give an example to simulate this situation

**Comment by shirleyStorage** [comment]
@dosu If the physical machine suddenly goes down, this removeSelfServerInfo will not be called and the serverinfo will stay there forever, right?

**Comment by shirleyStorage** [comment]
@dosu If this is the case, how do I clear serverInfo manually?

**Comment by shirleyStorage** [comment]
@dosu If I set server.role=computer, does it not check if serverinfo exists?

**Comment by shirleyStorage** [comment]
@dosu Does it still trigger `The server with name 'server-1' already in cluster`

**Comment by shirleyStorage** [comment]
@dosu What is the difference between hugegraph using master-worker pattern and backend=hstore pattern？

**Comment by shirleyStorage** [comment]
@dosu If  disable the master-worker pattern, are there other implementations that will work instead?

**Comment by shirleyStorage** [comment]
@dosu If I set server.role=computer,and use backend=rocksdb , start a standalone cluster.  
Then request ```curl -DELETE "http://localhost:8080/graphs/policy/schema/vertexlabels/person ```
it will return "can't schedule task on non-master server".how to resolve it?

**Comment by shirleyStorage** [comment]
@dosu 
I want to deprecated ```server.role=master```, so I can't set ```server.role=master```.I have to set server.role=computer,
, then I set  backend=rocksdb , start a standalone cluster.
To request curl -DELETE "http://localhost:8080/graphs/policy/schema/vertexlabels/person 
it will return "can't schedule task on non-master server". 

How can I fix it by improving the code?

**Comment by shirleyStorage** [comment]
@dosu How do I know if my cluster is standalone in the code？

**Comment by shirleyStorage** [comment]
@dosu If I set backend=rocksdb, is there definitely only one server node?
