### ISSUE TITLE
[Bug] Write Data Failed

### ISSUE THREAD

**Issue by JackyYangPassion** [apache/incubator-hugegraph#2717]
### Bug Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.5.0
- Backend: HStore
- OS: mac
- Data Size:  10 vertices, 10 edges 

### Expected & Actual behavior (期望与实际表现)

# Loader log
```
2024-12-30 20:40:05 [main] [ERROR] o.a.h.l.u.Printer [] - Failed to load, cause: Failed to update/query TaskStore: java.lang.InterruptedException
org.apache.hugegraph.exception.ServerException: Failed to update/query TaskStore: java.lang.InterruptedException
	at org.apache.hugegraph.exception.ServerException.fromResponse(ServerException.java:45) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:317) ~[hugegraph-common-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:253) ~[hugegraph-common-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:48) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:231) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:226) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:145) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:128) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:52) ~[hugegraph-client-1.5.0.jar:1.5.0]
	at com.sun.proxy.$Proxy33.create(Unknown Source) ~[?:?]
	at org.apache.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[apache-hugegraph-loader-incubating-1.5.0-shaded.jar:1.5.0]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[apache-hugegraph-loader-incubating-1.5.0-shaded.jar:1.5.0]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) ~[apache-hugegraph-loader-incubating-1.5.0-shaded.jar:1.5.0]
	at Script1.run(Script1.groovy:38) ~[?:?]
	at org.apache.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:56) ~[hugegraph-loader-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:156) ~[hugegraph-loader-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:107) ~[hugegraph-loader-1.5.0.jar:1.5.0]
	at org.apache.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:71) ~[hugegraph-loader-1.5.0.jar:1.5.0]
Caused by: org.apache.hugegraph.exception.ServerException$ServerCause: java.lang.InterruptedException

```

# HStore Log

```
2024-12-30 20:47:36 [ partition-hb] [ERROR] o.a.h.s.u.Version - Version.getVersion exception: 
java.lang.NullPointerException: null
	at org.apache.hugegraph.store.util.Version.getVersion(Version.java:36) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.meta.Store.<init>(Store.java:67) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.pd.DefaultPdProvider.getStoreByID(DefaultPdProvider.java:402) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.meta.PartitionManager.getStore(PartitionManager.java:674) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.meta.PartitionManager.lambda$getShardByRaftEndpoint$12(PartitionManager.java:839) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.apache.hugegraph.store.meta.PartitionManager.getShardByRaftEndpoint(PartitionManager.java:838) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.PartitionEngine.lambda$getAlivePeers$11(PartitionEngine.java:524) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.apache.hugegraph.store.PartitionEngine.getAlivePeers(PartitionEngine.java:523) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.HeartbeatService.partitionHeartbeat(HeartbeatService.java:307) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.HeartbeatService.doPartitionHeartbeat(HeartbeatService.java:156) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at org.apache.hugegraph.store.HeartbeatService$2.run(HeartbeatService.java:100) ~[hg-store-core-1.5.0.jar!/:1.5.0]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]


```

Schema Create Success But Write Vertex Failed

**Comment by JackyYangPassion** [comment]
build from master is running success!!
