### ISSUE TITLE
count() 查询报错

### ISSUE THREAD

**Issue by fisherinbox** [apache/incubator-hugegraph#37]
千万级别的点数据,以hbase作为存储,使用 g.V().count()查询会报超时,改了超时配置之后还是会报hbase相关的错误
java.io.InterruptedIOException: null
    at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:214) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:58) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithoutRetries(RpcRetryingCallerImpl.java:192) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:269) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:437) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ClientScanner.nextWithSyncCache(ClientScanner.java:312) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:597) ~[hbase-client-2.0.0.jar:2.0.0]
    at org.apache.hadoop.hbase.client.ResultScanner$1.hasNext(ResultScanner.java:53) ~[hbase-client-2.0.0.jar:2.0.0]
    at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$RowIterator.hasNext(HbaseSessions.java:474) ~[hugegraph-hbase-0.7.4.jar:?]
    at com.baidu.hugegraph.backend.serializer.BinaryEntryIterator.fetch(BinaryEntryIterator.java:71) ~[hugegraph-core-0.7.4.jar:0.7.4.0]
    at com.baidu.hugegraph.backend.store.BackendEntryIterator.hasNext(BackendEntryIterator.java:55) ~[hugegraph-core-0.7.4.jar:0.7.4.0]
    at com.baidu.hugegraph.iterator.ExtendableIterator.fetch(ExtendableIterator.java:89) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
    at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
    at com.baidu.hugegraph.iterator.MapperIterator.fetch(MapperIterator.java:42) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
    at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
    at com.baidu.hugegraph.iterator.FilterIterator.fetch(FilterIterator.java:42) ~[hugegraph-common-1.4.9.jar:1.4.9.0]

**Comment by javeme** [comment]
从错误日志来看应该是超时了。
目前大部分NoSQL数据库都无法支持快速的count操作，hugegraph所依赖的后端存储包括Cassandra、HBase、RocksDB等NoSQL数据库，所以count操作实际上需要遍历整张表，一般来说数据量大的时候容易导致超时。
我们也在考虑使用其它的方法来解决这个问题，目前还没有一个比较完美的方案。如果有任何好的想法欢迎与我们分享。

**Comment by javeme** [comment]
@fisherinbox 目前已优化了count语句，千万级别可以尝试直接同步执行（可适当调大rest和gremlin超时），或者直接使用异步gremlin任务。
