### ISSUE TITLE
v0.10 failed to start with "Not found key AGGREGATE_TYPE"

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph#772]
### Expected behavior 期望表现
Throw Error: "The backend store version is inconsistent"

### Actual behavior 实际表现
```
2019-12-01 22:34:13 12654 [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error: 
java.lang.IllegalStateException: Not found key 'AGGREGATE_TYPE' from entry 0x07df: [�=~backend_info, �
={"version":"1.5"}, �=, �3=, �x=, �y=]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199) ~[guava-19.0.jar:?]
	at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.column(BinarySerializer.java:1117) ~[classes/:?]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readEnum(BinarySerializer.java:1040) ~[classes/:?]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readPropertyKey(BinarySerializer.java:972) ~[classes/:?]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readPropertyKey(BinarySerializer.java:853) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.deserialize(SchemaTransaction.java:369) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:313) ~[classes/:?]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:200) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:126) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:71) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:91) ~[classes/:?]
	at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:203) ~[classes/:?]
	at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:76) ~[classes/:?]
```

### Specifications of environment 环境信息
- hugegraph version: v0.10 with v0.9 rocksdb-data
- hugegraph backend: rocksdb

**Comment by javeme** [comment]
How to resolve：do not use the program of new version to connect to the data with old version.
